# Generated by Django 4.1.2 on 2022-12-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_menuscoreall'),
    ]

    operations = [
        migrations.CreateModel(
            name='resultall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=300)),
                ('menu', models.CharField(max_length=300)),
                ('emotion', models.CharField(default='', max_length=300, null=True)),
                ('season', models.CharField(default='', max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
