# Generated by Django 4.1.2 on 2022-12-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_resultall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultall',
            name='restaurant',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
