# Generated by Django 4.1.2 on 2022-12-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('emotion', models.CharField(default='', max_length=300, null=True)),
                ('season', models.CharField(default='', max_length=300, null=True)),
                ('click', models.CharField(default='', max_length=300, null=True)),
            ],
        ),
    ]
