# Generated by Django 4.1.2 on 2022-12-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_alter_log_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='log',
            table='log',
        ),
    ]
