# Generated by Django 4.1.2 on 2022-12-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_remove_comment_content_comment_고투웍_comment_구내식당_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='돌배기',
            new_name='돌배기집',
        ),
    ]
